### ISSUE TITLE
Add Trivia Questions

### ISSUE THREAD

**Issue by jzureich** [vanand74/MeliorationWeb2#10]
In order to identify robots, do we want to add a page at the very beginning of the study that includes a few common-sense trivia questions (e.g. True or False; Healthy dogs have exactly 3 legs)? Participants would only be able to participate in the rest of the study if they answer all of these correctly.

**Comment by Nmoleo64** [comment]
On the to-do list is to add a captcha using Google's reCaptcha. If you would like to and have some extra time, you could research how to setup one in the website. It should be pretty easy but I'm not sure.

**Comment by jzureich** [comment]
Okay, I can definitely try to do that. Although, do you know if your dad would prefer the reCaptcha or the trivia questions? I know at one point we were a little worried that a very sophisticated user could design a program capable of completing reCaptchas. But I don't know how worried we are.

**Comment by Nmoleo64** [comment]
We could always do both, but I think just the reCaptcha should be fine. It is made by Google and used by millions of sites to ensure that robots are kept out.
