### ISSUE TITLE
Disabling Previous Page Button during Attention-Check Prompt

### ISSUE THREAD

**Issue by jzureich** [vanand74/MeliorationWeb2#19]
When the app prompts “We will now ask you questions to test your understanding of the instructions” in the Production Period, the “Previous Page” button is not disabled before hitting "Ok" (like it is in the Practice Period). If I press the Previous Page button before hitting “Ok” on that prompt, then the prompt does not return again when I get back to that page, thereby halting my ability to proceed with the app.

**Comment by Nmoleo64** [comment]
Fixed
