### ISSUE TITLE
Consent Form "I do not agree"

### ISSUE THREAD

**Issue by jzureich** [vanand74/MeliorationWeb2#21]
When I click “I Do Not Agree” to the consent form, the message says “Are you sure that you do not agree? If you click Yes, then your session will end.” However, “Yes” is not an option, only “OK” is an option.

**Comment by Nmoleo64** [comment]
The box should say "OK" and "Cancel". In which browser does this occur? JavaScript does not appear to allow you to have a "Yes"/"No" box, only "OK"/"Cancel".

**Comment by Nmoleo64** [comment]
Fixed
