### ISSUE TITLE
Internet Explorer - JavaScript not Enabled

### ISSUE THREAD

**Issue by jzureich** [vanand74/MeliorationWeb2#23]
When I pull the app up on Internet Explorer 11, I get “Error: Your browser does not support JavaScript,” even though, I have gone into my Internet Explorer settings to ensure that all scripting is enabled. This seems like an Internet Explorer problem, but I wanted to post it here anyways.

**Comment by Nmoleo64** [comment]
We decided not to allow Internet Explorer. As of now, if you are not using Opera, Firefox, Chrome, or Safari, it will not let you continue.
