### ISSUE TITLE
Submitting Answer During Processing Gives Error

### ISSUE THREAD

**Issue by jzureich** [vanand74/MeliorationWeb2#8]
o	An error occurs if an answer is submitted while the page is loading (so if I submit, then submit again while the initial submit is being processed, an error will occur). This is not fatal (I just need to press okay on the error message and move on), but it could confuse participants. Can we deactivate the Javascript button for a second or so after each submission?

**Comment by Nmoleo64** [comment]
Yes, I can definitely do this. I am also going to try and make the website tell you that a question response row already exists in the database instead of it just throwing an error.

**Comment by Nmoleo64** [comment]
Fixed
